import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useApi } from '../../hooks/useApi';
import { FiTarget, FiCheckCircle, FiTrendingUp, FiPlayCircle, FiArrowRight } from 'react-icons/fi';
import { Card, CardContent } from '../../components/ui/card';
import { Button } from '../../components/ui/button';

export default function Home() {
  const { user } = useAuth();
  const { get, post } = useApi();
  const navigate = useNavigate();
  const [tasks, setTasks] = useState([]);
  const [profile, setProfile] = useState(null);

  // Safe fallbacks to prevent crash (tracking logic runs in V3 Engine)
  const pendingTasks = [];
  const completedToday = [];

  const [startingSession, setStartingSession] = useState(false);

  useEffect(() => {
    // We fetch patient profile to check baseline completion
    get(`/patients/${user.id}`).then(setProfile).catch(() => {});
  }, [user.id]);

  const handleStartSession = async () => {
    setStartingSession(true);
    try {
      const session = await post('/sessions', { patient_id: user.id });
      navigate(`/patient/session/${session.session_id}`);
    } catch (err) {
      console.error(err);
    }
    setStartingSession(false);
  };

  return (
    <div className="max-w-7xl mx-auto">
      {/* Welcome */}
      <div className="flex items-center gap-4 mb-8">
        <h1 className="text-4xl font-black uppercase tracking-tight text-black">
          Welcome, {user?.name || 'Patient'}!
        </h1>
        <div className="neo-badge bg-neo-secondary rotate-3 animate-bounce-subtle">TODAY</div>
      </div>

      {/* Baseline prompt */}
      {profile && !profile.baseline_completed && (
        <div className="bg-neo-secondary border-4 border-black shadow-[8px_8px_0px_0px_#000] p-6 flex items-center justify-between mb-8 -rotate-[0.5deg]">
          <div>
            <h3 className="text-black font-black text-xl uppercase">⚡ Baseline Assessment Required</h3>
            <p className="text-black/70 font-bold text-sm mt-1">Complete this first so your therapist can build your therapy plan.</p>
          </div>
          <Button onClick={() => navigate('/patient/baseline')} className="bg-black text-white border-4 border-black shadow-[4px_4px_0px_0px_#FF6B6B]">
            Start Now <FiArrowRight className="w-4 h-4" strokeWidth={3} />
          </Button>
        </div>
      )}

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
        {[
          { label: 'TASKS LEFT', value: pendingTasks.length, icon: FiTarget, bg: 'bg-neo-accent' },
          { label: 'DONE TODAY', value: completedToday.length, icon: FiCheckCircle, bg: 'bg-neo-secondary' },
          { label: 'WEEKLY SCORE', value: '—', icon: FiTrendingUp, bg: 'bg-neo-muted' },
        ].map(({ label, value, icon: Icon, bg }) => (
          <div key={label} className={`${bg} border-4 border-black shadow-[6px_6px_0px_0px_#000] p-6 neo-lift`}>
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 border-4 border-black bg-white flex items-center justify-center -rotate-3">
                <Icon className="w-7 h-7 text-black" strokeWidth={3} />
              </div>
              <div>
                <p className="text-5xl font-black text-black leading-none mb-1">{value}</p>
                <p className="text-xs font-black uppercase tracking-widest text-black/60">{label}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Daily Action */}
      <div className="flex items-center justify-between mb-6 border-b-4 border-black pb-4 mt-12">
        <h2 className="text-3xl font-black uppercase tracking-tight text-black flex items-center gap-3">
            <FiPlayCircle strokeWidth={3} /> Daily Practice
        </h2>
      </div>

      <div className="bg-white border-4 border-black shadow-[8px_8px_0px_0px_#000] p-12 text-center rotate-[0.5deg]">
        <h3 className="text-3xl font-black uppercase text-black mb-4">Ready to practice?</h3>
        <p className="font-bold text-black/60 text-lg mb-8 max-w-lg mx-auto uppercase">
            Start today's session generated by your therapist's plan.
        </p>
        <Button 
            size="lg" 
            onClick={handleStartSession} 
            disabled={startingSession || (profile && !profile.baseline_completed)} 
            className="text-2xl px-12 py-8 bg-neo-accent text-black border-4 border-black hover:bg-black hover:text-white transition-all shadow-[6px_6px_0px_0px_#000]"
        >
            {startingSession ? 'STARTING...' : 'START DAILY SESSION'} <FiArrowRight className="w-6 h-6 ml-3" strokeWidth={3} />
        </Button>
      </div>


    </div>
  );
}
